"""create razorpay test orders table

Revision ID: 139d8a2e0a15
Revises: a6fbd93f884b
Create Date: 2026-08-29 21:49:32.844632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '139d8a2e0a15'
down_revision: Union[str, Sequence[str], None] = 'a6fbd93f884b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('razorpay_test_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_order_id', sa.String(length=128), nullable=False),
    sa.Column('receipt', sa.String(length=128), nullable=False),
    sa.Column('amount_rupees', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('provider_order_status', sa.String(length=32), nullable=False),
    sa.Column('data_source', sa.String(length=64), nullable=False),
    sa.Column('provider_generated', sa.Boolean(), nullable=False),
    sa.Column('real_money', sa.Boolean(), nullable=False),
    sa.Column('customer_reference', sa.String(length=128), nullable=True),
    sa.Column('provider_payment_id', sa.String(length=128), nullable=True),
    sa.Column('latest_payment_event_id', sa.UUID(), nullable=True),
    sa.Column('outcome_status', sa.String(length=32), nullable=False),
    sa.Column('provider_response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("data_source = 'razorpay_test_checkout'", name='ck_razorpay_test_orders_data_source'),
    sa.CheckConstraint('amount_rupees > 0', name='ck_razorpay_test_orders_positive_amount'),
    sa.CheckConstraint('provider_generated = true', name='ck_razorpay_test_orders_provider_generated'),
    sa.CheckConstraint('real_money = false', name='ck_razorpay_test_orders_not_real_money'),
    sa.ForeignKeyConstraint(['latest_payment_event_id'], ['payment_events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_order_id', name='uq_razorpay_test_orders_provider_order'),
    sa.UniqueConstraint('provider', 'receipt', name='uq_razorpay_test_orders_provider_receipt')
    )
    op.create_index(op.f('ix_razorpay_test_orders_outcome_status'), 'razorpay_test_orders', ['outcome_status'], unique=False)
    op.create_index(op.f('ix_razorpay_test_orders_provider_order_id'), 'razorpay_test_orders', ['provider_order_id'], unique=False)
    op.create_index(op.f('ix_razorpay_test_orders_tenant_id'), 'razorpay_test_orders', ['tenant_id'], unique=False)
    op.create_index('razorpay_test_order_outcome_created_index', 'razorpay_test_orders', ['outcome_status', 'created_at'], unique=False)
    op.create_index('razorpay_test_order_payment_index', 'razorpay_test_orders', ['provider_payment_id'], unique=False)
    op.create_index('razorpay_test_order_tenant_created_index', 'razorpay_test_orders', ['tenant_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('razorpay_test_order_tenant_created_index', table_name='razorpay_test_orders')
    op.drop_index('razorpay_test_order_payment_index', table_name='razorpay_test_orders')
    op.drop_index('razorpay_test_order_outcome_created_index', table_name='razorpay_test_orders')
    op.drop_index(op.f('ix_razorpay_test_orders_tenant_id'), table_name='razorpay_test_orders')
    op.drop_index(op.f('ix_razorpay_test_orders_provider_order_id'), table_name='razorpay_test_orders')
    op.drop_index(op.f('ix_razorpay_test_orders_outcome_status'), table_name='razorpay_test_orders')
    op.drop_table('razorpay_test_orders')
    # ### end Alembic commands ###
