"""create payment events table

Revision ID: 187a71233929
Revises: e626e8648341
Create Date: 2026-08-23 00:52:42.468717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '187a71233929'
down_revision: Union[str, Sequence[str], None] = 'e626e8648341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('provider_payment_id', sa.String(length=128), nullable=True),
    sa.Column('payload_sha256', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processing_status', sa.String(length=32), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_event_id', name='uq_payment_events_provider_event_id')
    )
    op.create_index(op.f('ix_payment_events_event_type'), 'payment_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_payment_events_provider_payment_id'), 'payment_events', ['provider_payment_id'], unique=False)
    op.create_index(op.f('ix_payment_events_tenant_id'), 'payment_events', ['tenant_id'], unique=False)
    op.create_index('payment_event_status_received_index', 'payment_events', ['processing_status', 'received_at'], unique=False)
    op.create_index('payment_event_tenant_type_index', 'payment_events', ['tenant_id', 'event_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('payment_event_tenant_type_index', table_name='payment_events')
    op.drop_index('payment_event_status_received_index', table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_tenant_id'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_provider_payment_id'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_event_type'), table_name='payment_events')
    op.drop_table('payment_events')
    # ### end Alembic commands ###
