"""create recovery decisions table

Revision ID: 262dc316acff
Revises: 187a71233929
Create Date: 2026-08-23 04:25:44.299630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '262dc316acff'
down_revision: Union[str, Sequence[str], None] = '187a71233929'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recovery_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('recovery_case_id', sa.UUID(), nullable=False),
    sa.Column('case_state_version', sa.Integer(), nullable=False),
    sa.Column('recommended_action', sa.Enum('retry_payment', 'send_payment_link', 'request_payment_method_update', 'request_customer_authorization', 'human_review', 'stop_recovery', name='recovery_action_type'), nullable=False),
    sa.Column('final_action', sa.Enum('retry_payment', 'send_payment_link', 'request_payment_method_update', 'request_customer_authorization', 'human_review', 'stop_recovery', name='recovery_action_type'), nullable=True),
    sa.Column('policy_result', sa.Enum('pending', 'approved', 'modified', 'rejected', 'escalated', name='policy_result'), nullable=False),
    sa.Column('status', sa.Enum('proposed', 'scheduled', 'executed', 'cancelled', 'failed', name='recovery_decision_status'), nullable=False),
    sa.Column('recovery_probability', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('expected_recovery_rupees', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('estimated_action_cost_rupees', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('expected_net_value_rupees', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('reason_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('decision_inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('alternatives', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_source', sa.String(length=64), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('estimated_action_cost_rupees >= 0', name='recovery_decision_action_cost_non_negative'),
    sa.CheckConstraint('expected_recovery_rupees >= 0', name='recovery_decision_expected_recovery_non_negative'),
    sa.CheckConstraint('recovery_probability >= 0 AND recovery_probability <= 1', name='recovery_decision_probability_range'),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recovery_case_id', 'case_state_version', name='uq_recovery_decision_case_state_version')
    )
    op.create_index(op.f('ix_recovery_decisions_recovery_case_id'), 'recovery_decisions', ['recovery_case_id'], unique=False)
    op.create_index(op.f('ix_recovery_decisions_status'), 'recovery_decisions', ['status'], unique=False)
    op.create_index(op.f('ix_recovery_decisions_tenant_id'), 'recovery_decisions', ['tenant_id'], unique=False)
    op.create_index('recovery_decision_case_created_index', 'recovery_decisions', ['recovery_case_id', 'created_at'], unique=False)
    op.create_index('recovery_decision_status_schedule_index', 'recovery_decisions', ['status', 'scheduled_for'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(
        "recovery_decision_status_schedule_index",
        table_name="recovery_decisions",
    )

    op.drop_index(
        "recovery_decision_case_created_index",
        table_name="recovery_decisions",
    )

    op.drop_index(
        op.f("ix_recovery_decisions_tenant_id"),
        table_name="recovery_decisions",
    )

    op.drop_index(
        op.f("ix_recovery_decisions_status"),
        table_name="recovery_decisions",
    )

    op.drop_index(
        op.f("ix_recovery_decisions_recovery_case_id"),
        table_name="recovery_decisions",
    )

    op.drop_table("recovery_decisions")

    postgresql.ENUM(
        name="recovery_decision_status",
    ).drop(
        op.get_bind(),
        checkfirst=True,
    )

    postgresql.ENUM(
        name="policy_result",
    ).drop(
        op.get_bind(),
        checkfirst=True,
    )

    postgresql.ENUM(
        name="recovery_action_type",
    ).drop(
        op.get_bind(),
        checkfirst=True,
    )
