"""add provider execution audit fields

Revision ID: a6fbd93f884b
Revises: f5ec49f0b21e
Create Date: 2026-08-26 21:18:10.902012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a6fbd93f884b'
down_revision: Union[str, Sequence[str], None] = 'f5ec49f0b21e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recovery_decisions', sa.Column('execution_mode', sa.String(length=32), nullable=True))
    op.add_column('recovery_decisions', sa.Column('provider_action_id', sa.String(length=128), nullable=True))
    op.add_column('recovery_decisions', sa.Column('provider_reference_id', sa.String(length=40), nullable=True))
    op.add_column('recovery_decisions', sa.Column('provider_action_url', sa.Text(), nullable=True))
    op.add_column('recovery_decisions', sa.Column('provider_action_status', sa.String(length=32), nullable=True))
    op.add_column('recovery_decisions', sa.Column('provider_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_recovery_decisions_provider_action_status'), 'recovery_decisions', ['provider_action_status'], unique=False)
    op.create_unique_constraint('uq_recovery_decision_provider_action_id', 'recovery_decisions', ['provider_action_id'])
    op.create_unique_constraint('uq_recovery_decision_provider_reference_id', 'recovery_decisions', ['provider_reference_id'])
    op.create_check_constraint('recovery_decision_execution_mode_allowed', 'recovery_decisions', "execution_mode IS NULL OR execution_mode IN ('simulated', 'razorpay_test')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('recovery_decision_execution_mode_allowed', 'recovery_decisions', type_='check')
    op.drop_constraint('uq_recovery_decision_provider_reference_id', 'recovery_decisions', type_='unique')
    op.drop_constraint('uq_recovery_decision_provider_action_id', 'recovery_decisions', type_='unique')
    op.drop_index(op.f('ix_recovery_decisions_provider_action_status'), table_name='recovery_decisions')
    op.drop_column('recovery_decisions', 'provider_response')
    op.drop_column('recovery_decisions', 'provider_action_status')
    op.drop_column('recovery_decisions', 'provider_action_url')
    op.drop_column('recovery_decisions', 'provider_reference_id')
    op.drop_column('recovery_decisions', 'provider_action_id')
    op.drop_column('recovery_decisions', 'execution_mode')
    # ### end Alembic commands ###
