"""create ai shadow decisions table

Revision ID: c3cde3b27b6a
Revises: 262dc316acff
Create Date: 2026-08-23 17:46:45.411718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c3cde3b27b6a'
down_revision: Union[str, Sequence[str], None] = '262dc316acff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_shadow_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('recovery_case_id', sa.UUID(), nullable=False),
    sa.Column('production_decision_id', sa.UUID(), nullable=False),
    sa.Column('case_state_version', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('recommended_action', sa.String(length=64), nullable=True),
    sa.Column('recovery_probability', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('expected_recovery_rupees', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('estimated_action_cost_rupees', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('expected_net_value_rupees', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('reason_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('input_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('response_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('agrees_with_production', sa.Boolean(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("recommended_action IS NULL OR recommended_action IN ('retry_payment', 'send_payment_link', 'request_payment_method_update', 'request_customer_authorization', 'human_review', 'stop_recovery')", name='ai_shadow_decision_action_allowed'),
    sa.CheckConstraint("status IN ('pending', 'completed', 'failed', 'invalid')", name='ai_shadow_decision_status_allowed'),
    sa.CheckConstraint('estimated_action_cost_rupees IS NULL OR estimated_action_cost_rupees >= 0', name='ai_shadow_action_cost_non_negative'),
    sa.CheckConstraint('expected_recovery_rupees IS NULL OR expected_recovery_rupees >= 0', name='ai_shadow_expected_recovery_non_negative'),
    sa.CheckConstraint('latency_ms IS NULL OR latency_ms >= 0', name='ai_shadow_latency_non_negative'),
    sa.CheckConstraint('recovery_probability IS NULL OR ''(recovery_probability >= 0 ''AND recovery_probability <= 1)',name='ai_shadow_decision_probability_range'),
    sa.ForeignKeyConstraint(['production_decision_id'], ['recovery_decisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('production_decision_id', 'model_name', 'prompt_version', name='uq_ai_shadow_production_model_prompt')
    )
    op.create_index('ai_shadow_agreement_created_index', 'ai_shadow_decisions', ['agrees_with_production', 'created_at'], unique=False)
    op.create_index('ai_shadow_case_created_index', 'ai_shadow_decisions', ['recovery_case_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_ai_shadow_decisions_production_decision_id'), 'ai_shadow_decisions', ['production_decision_id'], unique=False)
    op.create_index(op.f('ix_ai_shadow_decisions_recovery_case_id'), 'ai_shadow_decisions', ['recovery_case_id'], unique=False)
    op.create_index(op.f('ix_ai_shadow_decisions_status'), 'ai_shadow_decisions', ['status'], unique=False)
    op.create_index(op.f('ix_ai_shadow_decisions_tenant_id'), 'ai_shadow_decisions', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_shadow_decisions_tenant_id'), table_name='ai_shadow_decisions')
    op.drop_index(op.f('ix_ai_shadow_decisions_status'), table_name='ai_shadow_decisions')
    op.drop_index(op.f('ix_ai_shadow_decisions_recovery_case_id'), table_name='ai_shadow_decisions')
    op.drop_index(op.f('ix_ai_shadow_decisions_production_decision_id'), table_name='ai_shadow_decisions')
    op.drop_index('ai_shadow_case_created_index', table_name='ai_shadow_decisions')
    op.drop_index('ai_shadow_agreement_created_index', table_name='ai_shadow_decisions')
    op.drop_table('ai_shadow_decisions')
    # ### end Alembic commands ###
