"""store recovered provider payment id

Revision ID: cdb78a3bf4cb
Revises: c1136fcfdf56
Create Date: 2026-08-30 09:23:07.827937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdb78a3bf4cb'
down_revision: Union[str, Sequence[str], None] = 'c1136fcfdf56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recovery_cases', sa.Column('recovered_provider_payment_id', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_recovery_cases_recovered_provider_payment_id'), 'recovery_cases', ['recovered_provider_payment_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recovery_cases_recovered_provider_payment_id'), table_name='recovery_cases')
    op.drop_column('recovery_cases', 'recovered_provider_payment_id')
    # ### end Alembic commands ###
