"""create recovery cases table

Revision ID: e626e8648341
Revises: 
Create Date: 2026-08-22 16:02:10.849238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e626e8648341'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recovery_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('provider_payment_id', sa.String(length=128), nullable=True),
    sa.Column('provider_subscription_id', sa.String(length=128), nullable=True),
    sa.Column('provider_customer_id', sa.String(length=128), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('original_amount_rupees', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('recoverable_amount_rupees', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('recovered_amount_rupees', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('intervention_cost_rupees', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('failure_category', sa.Enum('temporary_gateway_or_bank', 'insufficient_funds', 'invalid_or_expired_method', 'mandate_or_authorization', 'unknown', name='failure_category'), nullable=True),
    sa.Column('current_state', sa.Enum('DETECTED', 'DIAGNOSED', 'EVALUATING', 'READY', 'SCHEDULED', 'EXECUTING', 'WAITING_FOR_RETRY', 'WAITING_FOR_CUSTOMER', 'HUMAN_REVIEW', 'RECOVERED', 'EXHAUSTED', 'STOPPED', 'EXPIRED', name='recovery_case_state'), nullable=False),
    sa.Column('state_version', sa.Integer(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('communication_count', sa.Integer(), nullable=False),
    sa.Column('next_action_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recovery_deadline_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('intervention_cost_rupees >= 0', name='recovery_case_intervention_cost_non_negative'),
    sa.CheckConstraint('original_amount_rupees >= 0', name='recovery_case_original_amount_non_negative'),
    sa.CheckConstraint('provider_payment_id IS NOT NULL OR provider_subscription_id IS NOT NULL', name='recovery_case_provider_reference_required'),
    sa.CheckConstraint('recoverable_amount_rupees <= original_amount_rupees', name='recovery_case_recoverable_within_original'),
    sa.CheckConstraint('recoverable_amount_rupees >= 0', name='recovery_case_recoverable_amount_non_negative'),
    sa.CheckConstraint('recovered_amount_rupees <= original_amount_rupees', name='recovery_case_recovered_within_original'),
    sa.CheckConstraint('recovered_amount_rupees >= 0', name='recovery_case_recovered_amount_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_cases_current_state'), 'recovery_cases', ['current_state'], unique=False)
    op.create_index(op.f('ix_recovery_cases_provider_payment_id'), 'recovery_cases', ['provider_payment_id'], unique=False)
    op.create_index(op.f('ix_recovery_cases_provider_subscription_id'), 'recovery_cases', ['provider_subscription_id'], unique=False)
    op.create_index(op.f('ix_recovery_cases_tenant_id'), 'recovery_cases', ['tenant_id'], unique=False)
    op.create_index('recovery_case_state_next_action_index', 'recovery_cases', ['current_state', 'next_action_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('recovery_case_state_next_action_index', table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_tenant_id'), table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_provider_subscription_id'), table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_provider_payment_id'), table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_current_state'), table_name='recovery_cases')
    op.drop_table('recovery_cases')
    # ### end Alembic commands ###
