"""create ml shadow decisions table

Revision ID: f5ec49f0b21e
Revises: c3cde3b27b6a
Create Date: 2026-08-26 01:37:14.765832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5ec49f0b21e'
down_revision: Union[str, Sequence[str], None] = 'c3cde3b27b6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_shadow_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('recovery_case_id', sa.UUID(), nullable=False),
    sa.Column('production_decision_id', sa.UUID(), nullable=False),
    sa.Column('case_state_version', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('calibration_method', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('selected_action', sa.String(length=64), nullable=True),
    sa.Column('raw_probability', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('calibrated_probability', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('expected_recovery_rupees', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('estimated_action_cost_rupees', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('expected_net_value_rupees', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('alternatives', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('input_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('agrees_with_production', sa.Boolean(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("selected_action IS NULL OR selected_action IN ('retry_payment', 'send_payment_link', 'request_payment_method_update', 'request_customer_authorization', 'human_review', 'stop_recovery')", name='ml_shadow_action_allowed'),
    sa.CheckConstraint("status IN ('pending', 'completed', 'failed', 'invalid')", name='ml_shadow_status_allowed'),
    sa.CheckConstraint('calibrated_probability IS NULL OR (calibrated_probability >= 0 AND calibrated_probability <= 1)', name='ml_shadow_calibrated_probability_range'),
    sa.CheckConstraint('estimated_action_cost_rupees IS NULL OR estimated_action_cost_rupees >= 0', name='ml_shadow_action_cost_non_negative'),
    sa.CheckConstraint('expected_recovery_rupees IS NULL OR expected_recovery_rupees >= 0', name='ml_shadow_expected_recovery_non_negative'),
    sa.CheckConstraint('latency_ms IS NULL OR latency_ms >= 0', name='ml_shadow_latency_non_negative'),
    sa.CheckConstraint('raw_probability IS NULL OR (raw_probability >= 0 AND raw_probability <= 1)', name='ml_shadow_raw_probability_range'),
    sa.ForeignKeyConstraint(['production_decision_id'], ['recovery_decisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('production_decision_id', 'model_name', 'model_version', name='uq_ml_shadow_production_model_version')
    )
    op.create_index(op.f('ix_ml_shadow_decisions_production_decision_id'), 'ml_shadow_decisions', ['production_decision_id'], unique=False)
    op.create_index(op.f('ix_ml_shadow_decisions_recovery_case_id'), 'ml_shadow_decisions', ['recovery_case_id'], unique=False)
    op.create_index(op.f('ix_ml_shadow_decisions_status'), 'ml_shadow_decisions', ['status'], unique=False)
    op.create_index(op.f('ix_ml_shadow_decisions_tenant_id'), 'ml_shadow_decisions', ['tenant_id'], unique=False)
    op.create_index('ml_shadow_agreement_created_index', 'ml_shadow_decisions', ['agrees_with_production', 'created_at'], unique=False)
    op.create_index('ml_shadow_case_created_index', 'ml_shadow_decisions', ['recovery_case_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ml_shadow_case_created_index', table_name='ml_shadow_decisions')
    op.drop_index('ml_shadow_agreement_created_index', table_name='ml_shadow_decisions')
    op.drop_index(op.f('ix_ml_shadow_decisions_tenant_id'), table_name='ml_shadow_decisions')
    op.drop_index(op.f('ix_ml_shadow_decisions_status'), table_name='ml_shadow_decisions')
    op.drop_index(op.f('ix_ml_shadow_decisions_recovery_case_id'), table_name='ml_shadow_decisions')
    op.drop_index(op.f('ix_ml_shadow_decisions_production_decision_id'), table_name='ml_shadow_decisions')
    op.drop_table('ml_shadow_decisions')
    # ### end Alembic commands ###
